### PR TITLE
High level outline

### PR DESCRIPTION
**Pull request by JaviSoto**

### CODE REVIEW

**Comment by JaviSoto** [comment]
cc @NachoSoto @jspahrsummers @neilpa @joshaber

Feel free to comment and give feedback :) This is for my talk on Thursday at the Swift Summit.

**Comment by neilpa** [comment]
What's your general goal/theme for the talk? I can't tell for sure from the outline. I'm hopeful it's how to unify existing async code under RAC by wrapping existing patterns. That's not something I've seen much of and would make for a good talk.

**Comment by JaviSoto** [comment]
Thanks a lot!

Yeah, good point. The angle is more from the perspective of someone who has never used RAC, or has tried it but was never convinced / understood the value. So I'm not trying to sell RAC specifically, just show that there's value in the ideas behind it, and that it can help you build iOS apps more easily.

>I'm hopeful it's how to unify existing async code under RAC

Yeah, I think that's a main part. Maybe from a slightly different point of view: how does an API look like with signals vs traditional completion blocks, and why is one better than the other. Is that kind of what you meant?

**Comment by neilpa** [comment]
> Is that kind of what you meant?

Yea, that clarifies it for me.

**Pull request merged**
